# ASP.NET Core

trigger:
- master

pool:
  name: Local #self hosted

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(6dc63482-5c20-4825-b210-5742695ad901)'
    command: 'build'
